version: '3.7'
services:
    postgres:
        image: postgres:10-alpine
        restart: always
        environment:
          - DEBUG=true
          - POSTGRES_DB=app
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres:/var/lib/postgresql/data

    app:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
          - "postgres"
        ports:
          - '5000:5000'
        volumes: 
          - /app/node_modules
          - .:/app
    
    # ui:
    #     stdin_open: true
    #     environment:
    #       - CHOKIDAR_USEPOLLING=true
    #     build:
    #       dockerfile: Dockerfile
    #       context: ./ui
    #     volumes:
    #       - /app/node_modules
    #       - .:/app