version: '3.7'
services:
    postgres:
        image: postgres:10-alpine
        restart: always
        environment:
          - DEBUG=true
          - POSTGRES_DB=app
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres:/var/lib/postgresql/data

    app:
        container_name: app
        hostname: app
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
          - "postgres"
        ports:
          - '5000:5000'
        volumes: 
          - /app/node_modules
          - ./:/app

    # adminui:
    #     container_name: adminui
    #     hostname: adminui
    #     build:
    #       context: ./adminui
    #       dockerfile: Dockerfile
    #     ports:
    #       - '5002:80'
    #     volumes: 
    #       - /adminui/node_modules
    #       - ./:/adminui
    
    # ui:
    #     container_name: ui
    #     hostname: ui
    #     build:
    #       context: ./ui
    #       dockerfile: Dockerfile
    #     ports:
    #       - '5001:80'
    #     volumes: 
    #       - /ui/node_modules
    #       - ./:/ui
    
    


