version: '3.7'
services:
    postgres:
        image: postgres:10-alpine
        restart: always
        environment:
          - DEBUG=true
          - POSTGRES_DB=app
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres:/var/lib/postgresql/data

    app:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
          - "postgres"
        ports:
          - '5000:5000'
        volumes: 
          - /app/node_modules
          - ./:/app
    
    ui:
        stdin_open: true
        environment:
          - CHOKIDAR_USEPOLLING=true
        build:
          dockerfile: Dockerfile
          context: ./ui
        ports:
          - '3000:3000'
        volumes:
          - /app/node_modules
          - ./ui:/app

    adminui:
        stdin_open: true
        environment:
          - CHOKIDAR_USEPOLLING=true
        build:
          dockerfile: Dockerfile
          context: ./adminui
        ports:
          - '3001:3000'
        volumes:
          - /app/node_modules
          - ./adminui:/app
    
    # nginx:
    #     depends_on:
    #       - app
    #       - ui
    #     restart: always
    #     build:
    #       dockerfile: Dockerfile
    #       context: ./nginx
    #     ports:
    #       - "3050:80"

