export const products = [
  {
    id: 1,
    url: "http://dummyimage.com/136x100.png/dddddd/000000",
    brand: "Globus",
    title: "Heroes for Sale",
    description: "Alteration of Left Shoulder Region, Percutaneous Approach",
    metadata: "Underdosing of other hormone antagonists, sequela",
    trending: true,
    stockQuantity: 33157,
    soldQuantity: 82915,
    price: 21858,
    salePrice: 58094,
    sizes: "2XL",
    categories: "Wedding dress",
    rating: 4.76,
  },
  {
    id: 2,
    url: "http://dummyimage.com/133x100.png/dddddd/000000",
    brand: "FabIndia",
    title: "Private Affairs of Bel Ami, The",
    description:
      "Replacement of Left Renal Vein with Synthetic Substitute, Open Approach",
    metadata: "Corrosion of unsp degree of left scapular region, init",
    trending: true,
    stockQuantity: 2822,
    soldQuantity: 71539,
    price: 50378,
    salePrice: 73564,
    sizes: "2XL",
    categories: "Top",
    rating: 5.74,
  },
  {
    id: 3,
    url: "http://dummyimage.com/172x100.png/dddddd/000000",
    brand: "Pepe Jeans",
    title: "Sun Alley (Sonnenallee)",
    description:
      "Insertion of Infusion Device into Left Face Vein, Open Approach",
    metadata: "Oth rheumatoid arthritis w rheumatoid factor of right wrist",
    trending: false,
    stockQuantity: 15880,
    soldQuantity: 73702,
    price: 48403,
    salePrice: 72556,
    sizes: "3XL",
    categories: "T-Shirt",
    rating: 6.25,
  },
  {
    id: 4,
    url: "http://dummyimage.com/179x100.png/cc0000/ffffff",
    brand: "WESTSIDE",
    title: "Public Housing",
    description:
      "Release Right Large Intestine, Via Natural or Artificial Opening",
    metadata: "Malignant neoplasm of overlapping sites of unsp male breast",
    trending: false,
    stockQuantity: 5058,
    soldQuantity: 25521,
    price: 28872,
    salePrice: 15695,
    sizes: "XL",
    categories: "Underwear",
    rating: 7.7,
  },
  {
    id: 5,
    url: "http://dummyimage.com/239x100.png/dddddd/000000",
    brand: "Stalkbuylove",
    title: "History of Hell (Rosas Höllenfahrt)",
    description:
      "Removal of Drainage Device from Right Upper Extremity, External Approach",
    metadata: "Unsp fx shaft of left fibula, subs for clos fx w routn heal",
    trending: true,
    stockQuantity: 42603,
    soldQuantity: 23423,
    price: 91538,
    salePrice: 95118,
    sizes: "XS",
    categories: "T-Shirt",
    rating: 1.38,
  },
  {
    id: 6,
    url: "http://dummyimage.com/176x100.png/ff4444/ffffff",
    brand: "Miss Chase",
    title: "Hedgehog, The (Le hérisson)",
    description:
      "Removal of Internal Fixation Device from Right Humeral Head, Open Approach",
    metadata: "Asphyxiation due to hanging, intentional self-harm",
    trending: true,
    stockQuantity: 81134,
    soldQuantity: 47555,
    price: 20654,
    salePrice: 99591,
    sizes: "M",
    categories: "Jeans",
    rating: 6.18,
  },
  {
    id: 7,
    url: "http://dummyimage.com/249x100.png/dddddd/000000",
    brand: "H&M",
    title: "Conquest of the Planet of the Apes",
    description:
      "Dilation of Left Lacrimal Duct with Intraluminal Device, Via Natural or Artificial Opening",
    metadata: "Superficial foreign body, unspecified lesser toe(s), sequela",
    trending: false,
    stockQuantity: 23217,
    soldQuantity: 15649,
    price: 68869,
    salePrice: 76549,
    sizes: "2XL",
    categories: "Skirt",
    rating: 7.55,
  },
  {
    id: 8,
    url: "http://dummyimage.com/117x100.png/cc0000/ffffff",
    brand: "Chumbak",
    title: "The Thief",
    description:
      "Drainage of Left Eustachian Tube, Via Natural or Artificial Opening Endoscopic, Diagnostic",
    metadata: "Nelson's syndrome",
    trending: true,
    stockQuantity: 40387,
    soldQuantity: 14412,
    price: 26823,
    salePrice: 80779,
    sizes: "2XL",
    categories: "Top",
    rating: 3.63,
  },
  {
    id: 9,
    url: "http://dummyimage.com/175x100.png/ff4444/ffffff",
    brand: "WESTSIDE",
    title: "Halloween",
    description:
      "Revision of Autologous Tissue Substitute in Thoracolumbar Vertebral Joint, External Approach",
    metadata: "Driver of pk-up/van inj in clsn w 2/3-whl mv in traf, sqla",
    trending: false,
    stockQuantity: 3082,
    soldQuantity: 22547,
    price: 44217,
    salePrice: 8572,
    sizes: "3XL",
    categories: "Top",
    rating: 6.56,
  },
  {
    id: 10,
    url: "http://dummyimage.com/222x100.png/ff4444/ffffff",
    brand: "Global Desi",
    title: "My Man and I",
    description:
      "Reposition Left Femoral Shaft, Percutaneous Endoscopic Approach",
    metadata: "Idiopathic chronic gout, unsp ankle and foot, without tophus",
    trending: false,
    stockQuantity: 40888,
    soldQuantity: 88642,
    price: 53734,
    salePrice: 92172,
    sizes: "S",
    categories: "Kurti",
    rating: 2.76,
  },
  {
    id: 11,
    url: "http://dummyimage.com/235x100.png/ff4444/ffffff",
    brand: "Pepe Jeans",
    title: "Murder Ahoy",
    description:
      "Bypass Superior Vena Cava to Pulmonary Vein Confluence with Synthetic Substitute, Open Approach",
    metadata: "Disp fx of body of unsp calcaneus, init for clos fx",
    trending: false,
    stockQuantity: 4802,
    soldQuantity: 31327,
    price: 48488,
    salePrice: 26327,
    sizes: "2XL",
    categories: "Jacket",
    rating: 5.07,
  },
  {
    id: 12,
    url: "http://dummyimage.com/162x100.png/5fa2dd/ffffff",
    brand: "Stalkbuylove",
    title: "Faces of Death 4",
    description: "Insertion of Monitoring Device into Duodenum, Open Approach",
    metadata: "Other superficial bite of unspecified upper arm, subs encntr",
    trending: true,
    stockQuantity: 1117,
    soldQuantity: 7500,
    price: 42869,
    salePrice: 76948,
    sizes: "XL",
    categories: "T-Shirt",
    rating: 4.43,
  },
  {
    id: 13,
    url: "http://dummyimage.com/127x100.png/ff4444/ffffff",
    brand: "Biba",
    title: "Road House",
    description:
      "Division of Right Abdomen Tendon, Percutaneous Endoscopic Approach",
    metadata: "Assault by other specified means",
    trending: true,
    stockQuantity: 27468,
    soldQuantity: 50095,
    price: 99452,
    salePrice: 61089,
    sizes: "S",
    categories: "Hoodie",
    rating: 6.15,
  },
  {
    id: 14,
    url: "http://dummyimage.com/116x100.png/dddddd/000000",
    brand: "Aurelia",
    title: "Hi-Life",
    description:
      "Insertion of Artificial Sphincter into Bladder Neck, Open Approach",
    metadata: "Pressure ulcer of right ankle, unspecified stage",
    trending: true,
    stockQuantity: 87567,
    soldQuantity: 64065,
    price: 2965,
    salePrice: 62560,
    sizes: "XL",
    categories: "Wedding dress",
    rating: 2.74,
  },
  {
    id: 15,
    url: "http://dummyimage.com/136x100.png/5fa2dd/ffffff",
    brand: "H&M",
    title: "Titicut Follies",
    description: "Beam Radiation of Lung using Electrons, Intraoperative",
    metadata: "Displacement of int fix of unsp bone of limb, init",
    trending: true,
    stockQuantity: 18776,
    soldQuantity: 79819,
    price: 19480,
    salePrice: 16726,
    sizes: "XS",
    categories: "Shorts",
    rating: 5.37,
  },
  {
    id: 16,
    url: "http://dummyimage.com/240x100.png/ff4444/ffffff",
    brand: "Pepe Jeans",
    title: "Angel's Egg (Tenshi no tamago)",
    description: "Beam Radiation of Soft Palate using Electrons",
    metadata: "Esotropia",
    trending: false,
    stockQuantity: 29029,
    soldQuantity: 85519,
    price: 81668,
    salePrice: 53889,
    sizes: "S",
    categories: "Saree",
    rating: 9.52,
  },
  {
    id: 17,
    url: "http://dummyimage.com/128x100.png/dddddd/000000",
    brand: "Pepe Jeans",
    title: "Baxter, The",
    description:
      "Therapeutic Exercise Treatment of Circulatory System - Whole Body using Assistive, Adaptive, Supportive or Protective Equipment",
    metadata: "Contact with hay derrick, initial encounter",
    trending: true,
    stockQuantity: 78007,
    soldQuantity: 60596,
    price: 86054,
    salePrice: 30465,
    sizes: "XL",
    categories: "Wedding dress",
    rating: 2.82,
  },
  {
    id: 18,
    url: "http://dummyimage.com/215x100.png/dddddd/000000",
    brand: "Global Desi",
    title: "Perfect World, A",
    description:
      "Replacement of Intracranial Vein with Synthetic Substitute, Open Approach",
    metadata: "Perf due to fb acc left in body following kidney dialysis",
    trending: true,
    stockQuantity: 95254,
    soldQuantity: 79897,
    price: 49851,
    salePrice: 40031,
    sizes: "3XL",
    categories: "Shorts",
    rating: 3.09,
  },
  {
    id: 19,
    url: "http://dummyimage.com/133x100.png/dddddd/000000",
    brand: "Allen Solly",
    title: "Medicine for Melancholy",
    description: "Destruction of Nasopharynx, Open Approach",
    metadata: "Traum hemor cereb, w LOC >24 hr w/o ret consc w surv, subs",
    trending: false,
    stockQuantity: 35840,
    soldQuantity: 7438,
    price: 13559,
    salePrice: 95863,
    sizes: "XS",
    categories: "Shorts",
    rating: 7.72,
  },
  {
    id: 20,
    url: "http://dummyimage.com/177x100.png/ff4444/ffffff",
    brand: "Globus",
    title: "Camille Rewinds",
    description:
      "Bypass Lower Esophagus to Jejunum with Autologous Tissue Substitute, Open Approach",
    metadata: "Open bite of right index finger with damage to nail",
    trending: false,
    stockQuantity: 89797,
    soldQuantity: 14993,
    price: 65200,
    salePrice: 72122,
    sizes: "3XL",
    categories: "T-Shirt",
    rating: 1.68,
  },
  {
    id: 21,
    url: "http://dummyimage.com/105x100.png/dddddd/000000",
    brand: "W for Women The label - Ritu Kumar",
    title: "Trailer Park Boys: Countdown to Liquor Day",
    description:
      "Destruction of Right Greater Saphenous Vein, Percutaneous Approach",
    metadata: "Neoplasm of uncertain behavior of cnsl, unsp",
    trending: false,
    stockQuantity: 5543,
    soldQuantity: 20240,
    price: 8731,
    salePrice: 36070,
    sizes: "L",
    categories: "Top",
    rating: 2.65,
  },
  {
    id: 22,
    url: "http://dummyimage.com/116x100.png/cc0000/ffffff",
    brand: "Pantaloons",
    title: "Worthless, The (Arvottomat)",
    description:
      "Excision of Lumbosacral Disc, Percutaneous Endoscopic Approach",
    metadata: "Disp fx of intermediate cuneiform of unspecified foot",
    trending: true,
    stockQuantity: 32977,
    soldQuantity: 37236,
    price: 68183,
    salePrice: 95344,
    sizes: "M",
    categories: "Jacket",
    rating: 3.96,
  },
  {
    id: 23,
    url: "http://dummyimage.com/244x100.png/5fa2dd/ffffff",
    brand: "H&M",
    title: "Siegfried & Roy: The Magic Box",
    description:
      "Replacement of Left Femoral Vein with Autologous Tissue Substitute, Open Approach",
    metadata: "Corrosion of first degree of nose (septum), init encntr",
    trending: true,
    stockQuantity: 83108,
    soldQuantity: 84616,
    price: 66622,
    salePrice: 53943,
    sizes: "XL",
    categories: "Leggings",
    rating: 1.09,
  },
  {
    id: 24,
    url: "http://dummyimage.com/246x100.png/5fa2dd/ffffff",
    brand: "Global Desi",
    title: "Patton Oswalt: My Weakness Is Strong",
    description:
      "Removal of Internal Fixation Device from Left Wrist Joint, Percutaneous Approach",
    metadata: "Toxic effect of venom of caterpillars, assault, subs encntr",
    trending: false,
    stockQuantity: 90285,
    soldQuantity: 72329,
    price: 48824,
    salePrice: 53345,
    sizes: "XL",
    categories: "Hoodie",
    rating: 3.89,
  },
  {
    id: 25,
    url: "http://dummyimage.com/132x100.png/cc0000/ffffff",
    brand: "W for Women The label - Ritu Kumar",
    title: "Falling in Love Again",
    description:
      "Alteration of Chest Wall with Autologous Tissue Substitute, Percutaneous Endoscopic Approach",
    metadata: "Prph T-cell lymph, not class, nodes of axilla and upper limb",
    trending: false,
    stockQuantity: 59973,
    soldQuantity: 8671,
    price: 82157,
    salePrice: 93095,
    sizes: "XS",
    categories: "Shorts",
    rating: 3.9,
  },
  {
    id: 26,
    url: "http://dummyimage.com/182x100.png/dddddd/000000",
    brand: "Madame or Glamly",
    title: "Stir Crazy",
    description:
      "Computerized Tomography (CT Scan) of Left Upper Arm using High Osmolar Contrast",
    metadata: "Other chronic hematogenous osteomyelitis, multiple sites",
    trending: false,
    stockQuantity: 67294,
    soldQuantity: 92748,
    price: 27114,
    salePrice: 79106,
    sizes: "S",
    categories: "Kurti",
    rating: 7.15,
  },
  {
    id: 27,
    url: "http://dummyimage.com/148x100.png/cc0000/ffffff",
    brand: "FabIndia",
    title: "Jim Gaffigan: Mr. Universe",
    description:
      "Reposition Right Femoral Shaft with Ring External Fixation Device, Open Approach",
    metadata: "Major contusion of spleen, sequela",
    trending: false,
    stockQuantity: 31729,
    soldQuantity: 4606,
    price: 33373,
    salePrice: 30302,
    sizes: "XS",
    categories: "Kurti",
    rating: 7.44,
  },
  {
    id: 28,
    url: "http://dummyimage.com/242x100.png/5fa2dd/ffffff",
    brand: "Pantaloons",
    title: "Gulliver's Travels",
    description: "Release Lesser Omentum, Open Approach",
    metadata: "Acute mastoiditis without complications, bilateral",
    trending: false,
    stockQuantity: 94792,
    soldQuantity: 62215,
    price: 99240,
    salePrice: 76057,
    sizes: "L",
    categories: "Shorts",
    rating: 2.13,
  },
  {
    id: 29,
    url: "http://dummyimage.com/222x100.png/5fa2dd/ffffff",
    brand: "Bombay Selection",
    title: "Sleuth",
    description:
      "Supplement Large Intestine with Nonautologous Tissue Substitute, Via Natural or Artificial Opening",
    metadata: "Lac w/o fb of left lesser toe(s) w/o damage to nail, sequela",
    trending: true,
    stockQuantity: 55281,
    soldQuantity: 99382,
    price: 5829,
    salePrice: 63603,
    sizes: "S",
    categories: "Shorts",
    rating: 6.1,
  },
  {
    id: 30,
    url: "http://dummyimage.com/191x100.png/cc0000/ffffff",
    brand: "Bombay Selection",
    title: "Yogi Bear",
    description:
      "Extirpation of Matter from Ascending Colon, Percutaneous Approach",
    metadata: "Mtrcy driver injured in nonclsn trnsp accident in traf, subs",
    trending: true,
    stockQuantity: 17696,
    soldQuantity: 62009,
    price: 47216,
    salePrice: 40196,
    sizes: "M",
    categories: "Hoodie",
    rating: 2.6,
  },
  {
    id: 31,
    url: "http://dummyimage.com/240x100.png/ff4444/ffffff",
    brand: "Global Desi",
    title: "The Intruders",
    description: "Excision of Left Vocal Cord, Open Approach, Diagnostic",
    metadata: "Pressr ulc of contig site of back,buttock & hip, unstageable",
    trending: false,
    stockQuantity: 90643,
    soldQuantity: 14998,
    price: 10770,
    salePrice: 99410,
    sizes: "XL",
    categories: "Wedding dress",
    rating: 8.65,
  },
  {
    id: 32,
    url: "http://dummyimage.com/239x100.png/dddddd/000000",
    brand: "WESTSIDE",
    title: "Windows",
    description: "Resection of Cystic Duct, Percutaneous Endoscopic Approach",
    metadata: "Corrosion of unspecified degree of left ankle, sequela",
    trending: true,
    stockQuantity: 36481,
    soldQuantity: 88809,
    price: 61838,
    salePrice: 60227,
    sizes: "S",
    categories: "Shorts",
    rating: 5.3,
  },
  {
    id: 33,
    url: "http://dummyimage.com/182x100.png/ff4444/ffffff",
    brand: "AND",
    title: "Once Bitten",
    description:
      "Drainage of Left Adrenal Gland, Percutaneous Endoscopic Approach",
    metadata: "Pasngr in hv veh inj in clsn w nonmtr vehicle in traf, init",
    trending: true,
    stockQuantity: 5812,
    soldQuantity: 73687,
    price: 59868,
    salePrice: 28303,
    sizes: "M",
    categories: "Jeans",
    rating: 5.69,
  },
  {
    id: 34,
    url: "http://dummyimage.com/235x100.png/ff4444/ffffff",
    brand: "Stalkbuylove",
    title: "Cold Trail (Köld slóð)",
    description:
      "Supplement Left Abdomen Bursa and Ligament with Synthetic Substitute, Percutaneous Endoscopic Approach",
    metadata: "Displ oblique fx shaft of unsp femr, 7thF",
    trending: true,
    stockQuantity: 32662,
    soldQuantity: 65228,
    price: 51186,
    salePrice: 35866,
    sizes: "2XL",
    categories: "Wedding dress",
    rating: 6.04,
  },
  {
    id: 35,
    url: "http://dummyimage.com/228x100.png/cc0000/ffffff",
    brand: "Miss Chase",
    title: "Doppelganger",
    description: "Extirpation of Matter from Splenic Vein, Open Approach",
    metadata: "Poisoning by antimycobacterial drugs, assault, sequela",
    trending: true,
    stockQuantity: 27757,
    soldQuantity: 23060,
    price: 35529,
    salePrice: 92999,
    sizes: "2XL",
    categories: "T-Shirt",
    rating: 4.76,
  },
  {
    id: 36,
    url: "http://dummyimage.com/112x100.png/dddddd/000000",
    brand: "Only",
    title: "Let It Ride",
    description: "Excision of Right Patella, Open Approach, Diagnostic",
    metadata: "Burn third degree of shldr/up lmb, except wrs/hnd, unsp site",
    trending: false,
    stockQuantity: 47085,
    soldQuantity: 15596,
    price: 73408,
    salePrice: 77748,
    sizes: "M",
    categories: "Wedding dress",
    rating: 9.9,
  },
  {
    id: 37,
    url: "http://dummyimage.com/160x100.png/dddddd/000000",
    brand: "Only",
    title: "Pokrajina St.2",
    description: "Release Facial Nerve, Percutaneous Endoscopic Approach",
    metadata: "Benign neoplasm of kidney",
    trending: true,
    stockQuantity: 45358,
    soldQuantity: 21859,
    price: 58674,
    salePrice: 21406,
    sizes: "3XL",
    categories: "Underwear",
    rating: 1.08,
  },
  {
    id: 38,
    url: "http://dummyimage.com/145x100.png/dddddd/000000",
    brand: "Stalkbuylove",
    title: "Anna: 6-18 (Anna: Ot shesti do vosemnadtsati)",
    description:
      "Restriction of Right Internal Jugular Vein, Percutaneous Approach",
    metadata: "Displaced longitudinal fracture of unsp patella, init",
    trending: true,
    stockQuantity: 33875,
    soldQuantity: 39824,
    price: 64692,
    salePrice: 48353,
    sizes: "XL",
    categories: "Jeans",
    rating: 1.58,
  },
  {
    id: 39,
    url: "http://dummyimage.com/207x100.png/5fa2dd/ffffff",
    brand: "Zara",
    title: "Kingdom II, The (Riget II)",
    description:
      "Revision of Extraluminal Device in Trachea, Percutaneous Endoscopic Approach",
    metadata: "Rh incompatibility w acute hemolytic transfs react, sequela",
    trending: false,
    stockQuantity: 86745,
    soldQuantity: 254,
    price: 87152,
    salePrice: 7885,
    sizes: "S",
    categories: "Jeans",
    rating: 4.94,
  },
  {
    id: 40,
    url: "http://dummyimage.com/204x100.png/dddddd/000000",
    brand: "Forever 21",
    title: "World's Fastest Indian, The",
    description:
      "Removal of Nonautologous Tissue Substitute from Hair, External Approach",
    metadata: "Corrosion of second degree of male genital region, subs",
    trending: true,
    stockQuantity: 57332,
    soldQuantity: 77034,
    price: 34878,
    salePrice: 8352,
    sizes: "XL",
    categories: "Skirt",
    rating: 7.46,
  },
  {
    id: 41,
    url: "http://dummyimage.com/194x100.png/ff4444/ffffff",
    brand: "Biba",
    title: "By the Law",
    description:
      "Removal of Autologous Tissue Substitute from Upper Extremity Subcutaneous Tissue and Fascia, Percutaneous Approach",
    metadata: "Displ bicondylar fx r tibia, 7thN",
    trending: true,
    stockQuantity: 87498,
    soldQuantity: 56318,
    price: 35681,
    salePrice: 93085,
    sizes: "3XL",
    categories: "Shorts",
    rating: 8.37,
  },
  {
    id: 42,
    url: "http://dummyimage.com/239x100.png/dddddd/000000",
    brand: "Stalkbuylove",
    title: "Pretty/Handsome",
    description:
      "Drainage of Right Lacrimal Duct, Via Natural or Artificial Opening Endoscopic, Diagnostic",
    metadata: "Car driver injured in collision w 2/3-whl mv in traf, init",
    trending: true,
    stockQuantity: 70933,
    soldQuantity: 31931,
    price: 21966,
    salePrice: 53675,
    sizes: "XL",
    categories: "Skirt",
    rating: 6.48,
  },
  {
    id: 43,
    url: "http://dummyimage.com/120x100.png/cc0000/ffffff",
    brand: "Miss Chase",
    title: "Big Star: Nothing Can Hurt Me",
    description:
      "Therapeutic Exercise Treatment of Genitourinary System using Prosthesis",
    metadata: "Unsp fracture of right forearm, init for opn fx type 3A/B/C",
    trending: true,
    stockQuantity: 42049,
    soldQuantity: 88200,
    price: 21375,
    salePrice: 2756,
    sizes: "S",
    categories: "Jeans",
    rating: 7.77,
  },
  {
    id: 44,
    url: "http://dummyimage.com/170x100.png/dddddd/000000",
    brand: "AND",
    title: "Country",
    description:
      "Fragmentation in Left Hepatic Duct, Via Natural or Artificial Opening",
    metadata: "Cannabis dependence with intoxication, uncomplicated",
    trending: false,
    stockQuantity: 43787,
    soldQuantity: 52831,
    price: 72500,
    salePrice: 58834,
    sizes: "M",
    categories: "Underwear",
    rating: 5.07,
  },
  {
    id: 45,
    url: "http://dummyimage.com/206x100.png/5fa2dd/ffffff",
    brand: "Madame or Glamly",
    title: "Bay of Angels (La baie des anges)",
    description:
      "Drainage of Left Knee Region, Percutaneous Endoscopic Approach",
    metadata: "Burn of 2nd deg mul left fingers (nail), not including thumb",
    trending: true,
    stockQuantity: 72636,
    soldQuantity: 61778,
    price: 6046,
    salePrice: 13206,
    sizes: "M",
    categories: "Kurti",
    rating: 3.67,
  },
  {
    id: 46,
    url: "http://dummyimage.com/201x100.png/ff4444/ffffff",
    brand: "WESTSIDE",
    title: "Gracie",
    description:
      "Dilation of Right Common Iliac Artery, Bifurcation, with Three Drug-eluting Intraluminal Devices, Open Approach",
    metadata: "Genetic susceptibility to malignant neoplasm of prostate",
    trending: true,
    stockQuantity: 43258,
    soldQuantity: 6572,
    price: 480,
    salePrice: 39857,
    sizes: "2XL",
    categories: "Hoodie",
    rating: 4.73,
  },
  {
    id: 47,
    url: "http://dummyimage.com/225x100.png/ff4444/ffffff",
    brand: "Stalkbuylove",
    title: "Harry and the Hendersons",
    description:
      "Dilation of Face Artery, Bifurcation, with Four or More Drug-eluting Intraluminal Devices, Open Approach",
    metadata: "Oth nondisp fx of lower end r humer, subs for fx w nonunion",
    trending: false,
    stockQuantity: 55245,
    soldQuantity: 49999,
    price: 28338,
    salePrice: 70897,
    sizes: "M",
    categories: "Leggings",
    rating: 7.38,
  },
  {
    id: 48,
    url: "http://dummyimage.com/194x100.png/ff4444/ffffff",
    brand: "Aurelia",
    title: "Enemy of the People, An",
    description:
      "Insertion of Reservoir into Right Upper Leg Subcutaneous Tissue and Fascia, Percutaneous Approach",
    metadata: "Driver of bus injured in collision w hv veh nontraf",
    trending: false,
    stockQuantity: 53825,
    soldQuantity: 96161,
    price: 99113,
    salePrice: 52731,
    sizes: "S",
    categories: "Skirt",
    rating: 7.53,
  },
  {
    id: 49,
    url: "http://dummyimage.com/241x100.png/cc0000/ffffff",
    brand: "Madame or Glamly",
    title: "Children of Men",
    description:
      "Repair Appendix, Via Natural or Artificial Opening Endoscopic",
    metadata: "Dislocation of C1/C2 cervical vertebrae",
    trending: true,
    stockQuantity: 90958,
    soldQuantity: 52308,
    price: 85192,
    salePrice: 45382,
    sizes: "S",
    categories: "Wedding dress",
    rating: 6.33,
  },
  {
    id: 50,
    url: "http://dummyimage.com/150x100.png/cc0000/ffffff",
    brand: "Levis",
    title: "Airheads",
    description:
      "Insertion of External Fixation Device into Left Humeral Head, Percutaneous Approach",
    metadata: "Underdosing of antiallergic and antiemetic drugs, subs",
    trending: false,
    stockQuantity: 49363,
    soldQuantity: 64771,
    price: 47768,
    salePrice: 10418,
    sizes: "XS",
    categories: "Jeans",
    rating: 9.01,
  },
  {
    id: 51,
    url: "http://dummyimage.com/107x100.png/cc0000/ffffff",
    brand: "Madame or Glamly",
    title: "Double Dynamite",
    description:
      "Fusion of Left Wrist Joint with External Fixation Device, Percutaneous Endoscopic Approach",
    metadata: "Hemorrhagic otitis externa, left ear",
    trending: true,
    stockQuantity: 78745,
    soldQuantity: 30314,
    price: 93951,
    salePrice: 80820,
    sizes: "M",
    categories: "Kurti",
    rating: 3.56,
  },
  {
    id: 52,
    url: "http://dummyimage.com/213x100.png/ff4444/ffffff",
    brand: "Aurelia",
    title: "Greatest Game Ever Played, The",
    description: "Drainage of Thalamus, Open Approach",
    metadata: "Laceration with foreign body of unsp elbow, subs encntr",
    trending: true,
    stockQuantity: 33190,
    soldQuantity: 38137,
    price: 38566,
    salePrice: 15847,
    sizes: "M",
    categories: "Jeans",
    rating: 1.31,
  },
  {
    id: 53,
    url: "http://dummyimage.com/163x100.png/dddddd/000000",
    brand: "FabIndia",
    title: "Fun with Dick and Jane",
    description:
      "Vocational Activities and Functional Community or Work Reintegration Skills Treatment using Prosthesis",
    metadata: "Pasngr on bus injured in clsn w statnry object nontraf, subs",
    trending: false,
    stockQuantity: 32808,
    soldQuantity: 83068,
    price: 54370,
    salePrice: 76326,
    sizes: "S",
    categories: "Shorts",
    rating: 9.16,
  },
  {
    id: 54,
    url: "http://dummyimage.com/218x100.png/dddddd/000000",
    brand: "AND",
    title: "Children of the Corn: Revelation",
    description: "Drainage of Vulva, External Approach",
    metadata: "Multiple fractures of ribs, bi, subs for fx w delay heal",
    trending: true,
    stockQuantity: 65202,
    soldQuantity: 1995,
    price: 86703,
    salePrice: 51722,
    sizes: "S",
    categories: "Underwear",
    rating: 1.73,
  },
  {
    id: 55,
    url: "http://dummyimage.com/177x100.png/cc0000/ffffff",
    brand: "Pepe Jeans",
    title: "Halo Legends",
    description:
      "Bypass Lower Esophagus to Stomach with Nonautologous Tissue Substitute, Open Approach",
    metadata: "Chronic sialoadenitis",
    trending: true,
    stockQuantity: 12772,
    soldQuantity: 65078,
    price: 56622,
    salePrice: 50639,
    sizes: "XL",
    categories: "T-Shirt",
    rating: 9.74,
  },
  {
    id: 56,
    url: "http://dummyimage.com/109x100.png/cc0000/ffffff",
    brand: "Global Desi",
    title: "Fjorton suger",
    description: "Drainage of Right Femoral Region, Percutaneous Approach",
    metadata: "Type III traum spondylolysis of 3rd cervcal vert, 7thD",
    trending: false,
    stockQuantity: 9400,
    soldQuantity: 95695,
    price: 97234,
    salePrice: 9809,
    sizes: "3XL",
    categories: "Wedding dress",
    rating: 9.45,
  },
  {
    id: 57,
    url: "http://dummyimage.com/243x100.png/dddddd/000000",
    brand: "Aurelia",
    title: "Incredibly True Adventure of Two Girls in Love, The",
    description: "Extraction of Chest Skin, External Approach",
    metadata: "Unspecified physeal fracture of lower end of right femur",
    trending: true,
    stockQuantity: 93106,
    soldQuantity: 26499,
    price: 27778,
    salePrice: 13197,
    sizes: "2XL",
    categories: "Saree",
    rating: 7.77,
  },
  {
    id: 58,
    url: "http://dummyimage.com/134x100.png/5fa2dd/ffffff",
    brand: "Globus",
    title: "Librarian: Quest for the Spear, The",
    description:
      "Replacement of Bilateral External Ear with Nonautologous Tissue Substitute, External Approach",
    metadata: "Lactose intolerance",
    trending: false,
    stockQuantity: 76310,
    soldQuantity: 10010,
    price: 60911,
    salePrice: 38382,
    sizes: "M",
    categories: "Underwear",
    rating: 7.97,
  },
  {
    id: 59,
    url: "http://dummyimage.com/124x100.png/cc0000/ffffff",
    brand: "AND",
    title: "After Death (Posle smerti)",
    description:
      "Bypass Right Renal Vein to Lower Vein with Synthetic Substitute, Open Approach",
    metadata: "Unsp larger firearm discharge, undetermined intent, sequela",
    trending: true,
    stockQuantity: 30530,
    soldQuantity: 94247,
    price: 12973,
    salePrice: 98673,
    sizes: "L",
    categories: "Shorts",
    rating: 6.92,
  },
  {
    id: 60,
    url: "http://dummyimage.com/203x100.png/cc0000/ffffff",
    brand: "Global Desi",
    title:
      "Right America: Feeling Wronged - Some Voices from the Campaign Trail ",
    description: "Repair Right Tibia, Open Approach",
    metadata: "Rheu arthritis w rheu factor of left knee w/o org/sys involv",
    trending: false,
    stockQuantity: 85778,
    soldQuantity: 94538,
    price: 61338,
    salePrice: 16350,
    sizes: "L",
    categories: "Saree",
    rating: 1.87,
  },
  {
    id: 61,
    url: "http://dummyimage.com/235x100.png/cc0000/ffffff",
    brand: "Aurelia",
    title: "Nowhere Boy",
    description:
      "Supplement Cisterna Chyli with Synthetic Substitute, Percutaneous Endoscopic Approach",
    metadata: "Dislocation of C4/C5 cervical vertebrae, subs encntr",
    trending: true,
    stockQuantity: 9965,
    soldQuantity: 83611,
    price: 57229,
    salePrice: 2285,
    sizes: "L",
    categories: "Shorts",
    rating: 9.95,
  },
  {
    id: 62,
    url: "http://dummyimage.com/177x100.png/cc0000/ffffff",
    brand: "Pantaloons",
    title: "Unreal Dream: The Michael Morton Story, An",
    description:
      "Drainage of Left Abdomen Muscle with Drainage Device, Percutaneous Approach",
    metadata: "Stable burst fx first cervcal vert, subs for fx w routn heal",
    trending: false,
    stockQuantity: 7465,
    soldQuantity: 98828,
    price: 59137,
    salePrice: 62306,
    sizes: "S",
    categories: "Underwear",
    rating: 9.26,
  },
  {
    id: 63,
    url: "http://dummyimage.com/237x100.png/5fa2dd/ffffff",
    brand: "Pepe Jeans",
    title: "Archangel",
    description: "Change Pressure Dressing on Left Upper Leg",
    metadata: "Accidental drown while in swimming-pool, subs",
    trending: false,
    stockQuantity: 86856,
    soldQuantity: 43112,
    price: 18760,
    salePrice: 2291,
    sizes: "S",
    categories: "Hoodie",
    rating: 4.21,
  },
  {
    id: 64,
    url: "http://dummyimage.com/201x100.png/dddddd/000000",
    brand: "AND",
    title: "Breakheart Pass",
    description:
      "Nuclear Medicine, Lymphatic and Hematologic System, Nonimaging Nuclear Medicine Probe",
    metadata: "Crohn's disease of large intestine w intestinal obstruction",
    trending: false,
    stockQuantity: 38445,
    soldQuantity: 58476,
    price: 53402,
    salePrice: 96019,
    sizes: "2XL",
    categories: "Jeans",
    rating: 7.79,
  },
  {
    id: 65,
    url: "http://dummyimage.com/208x100.png/5fa2dd/ffffff",
    brand: "Pantaloons",
    title: "Daniel Deronda",
    description:
      "Bypass Ileum to Ileum, Via Natural or Artificial Opening Endoscopic",
    metadata: "Disp fx of prox phalanx of r mid fngr, 7thP",
    trending: true,
    stockQuantity: 74666,
    soldQuantity: 59127,
    price: 71120,
    salePrice: 78638,
    sizes: "S",
    categories: "Jeans",
    rating: 6.25,
  },
  {
    id: 66,
    url: "http://dummyimage.com/162x100.png/ff4444/ffffff",
    brand: "Pepe Jeans",
    title: "Barcelona",
    description:
      "Dilation of Superior Mesenteric Artery with Drug-eluting Intraluminal Device, Percutaneous Endoscopic Approach",
    metadata: "Open bite of right thumb with damage to nail, sequela",
    trending: false,
    stockQuantity: 19911,
    soldQuantity: 909,
    price: 91971,
    salePrice: 33399,
    sizes: "S",
    categories: "Kurti",
    rating: 7.79,
  },
  {
    id: 67,
    url: "http://dummyimage.com/177x100.png/cc0000/ffffff",
    brand: "Only",
    title: "Silent House",
    description:
      "Revision of Internal Fixation Device in Left Patella, External Approach",
    metadata: "Athscl nonautologous bio bypass of the left leg w ulceration",
    trending: false,
    stockQuantity: 51432,
    soldQuantity: 18661,
    price: 5867,
    salePrice: 74290,
    sizes: "2XL",
    categories: "Jacket",
    rating: 6.3,
  },
  {
    id: 68,
    url: "http://dummyimage.com/172x100.png/5fa2dd/ffffff",
    brand: "Stalkbuylove",
    title: "Jailhouse Rock",
    description:
      "Drainage of Retroperitoneum, Percutaneous Endoscopic Approach",
    metadata: "Milt op involving explosion of guided missile, milt, sequela",
    trending: true,
    stockQuantity: 72077,
    soldQuantity: 65903,
    price: 30384,
    salePrice: 73797,
    sizes: "2XL",
    categories: "Shorts",
    rating: 1.78,
  },
  {
    id: 69,
    url: "http://dummyimage.com/110x100.png/dddddd/000000",
    brand: "Biba",
    title: "SS Camp 5: Women's Hell (SS Lager 5: L'inferno delle donne)",
    description: "Excision of Head Lymphatic, Percutaneous Approach",
    metadata: "Accidental malfunction of machine gun",
    trending: false,
    stockQuantity: 43814,
    soldQuantity: 69155,
    price: 13162,
    salePrice: 88753,
    sizes: "3XL",
    categories: "Saree",
    rating: 6.18,
  },
  {
    id: 70,
    url: "http://dummyimage.com/139x100.png/5fa2dd/ffffff",
    brand: "Chumbak",
    title: "24: Redemption",
    description:
      "Fusion of Right Metatarsal-Phalangeal Joint, Percutaneous Approach",
    metadata: "Narcolepsy in conditions classified elsewhere w/o cataplexy",
    trending: true,
    stockQuantity: 51754,
    soldQuantity: 62508,
    price: 14425,
    salePrice: 21013,
    sizes: "M",
    categories: "Underwear",
    rating: 4.05,
  },
  {
    id: 71,
    url: "http://dummyimage.com/106x100.png/cc0000/ffffff",
    brand: "Pantaloons",
    title: "Virginia's Run",
    description: "Release Left Internal Jugular Vein, Percutaneous Approach",
    metadata: "Poisoning by oth antipsychot/neurolept, self-harm",
    trending: true,
    stockQuantity: 5619,
    soldQuantity: 40927,
    price: 7945,
    salePrice: 84280,
    sizes: "L",
    categories: "Top",
    rating: 1.39,
  },
  {
    id: 72,
    url: "http://dummyimage.com/234x100.png/5fa2dd/ffffff",
    brand: "H&M",
    title: "Girl of Finland (Lapualaismorsian)",
    description:
      "Dilation of Left Pulmonary Vein with Intraluminal Device, Percutaneous Endoscopic Approach",
    metadata: "Contus/lac right cerebrum w/o loss of consciousness",
    trending: false,
    stockQuantity: 33958,
    soldQuantity: 32833,
    price: 99783,
    salePrice: 44689,
    sizes: "XS",
    categories: "Shorts",
    rating: 1.67,
  },
  {
    id: 73,
    url: "http://dummyimage.com/225x100.png/5fa2dd/ffffff",
    brand: "Pepe Jeans",
    title: "Bread and Chocolate (Pane e cioccolata)",
    description:
      "Bypass Left Femoral Artery to Posterior Tibial Artery with Autologous Arterial Tissue, Open Approach",
    metadata: "Puncture wound w foreign body of thmb w/o damage to nail",
    trending: true,
    stockQuantity: 83922,
    soldQuantity: 2934,
    price: 58792,
    salePrice: 25707,
    sizes: "XS",
    categories: "Top",
    rating: 2.45,
  },
  {
    id: 74,
    url: "http://dummyimage.com/166x100.png/ff4444/ffffff",
    brand: "Globus",
    title: "My Perestroika",
    description:
      "Dilation of Left Foot Artery with Four or More Intraluminal Devices, Percutaneous Endoscopic Approach",
    metadata: "Unsp superficial injuries of right back wall of thorax",
    trending: true,
    stockQuantity: 38171,
    soldQuantity: 88745,
    price: 67708,
    salePrice: 64612,
    sizes: "S",
    categories: "Top",
    rating: 9.46,
  },
  {
    id: 75,
    url: "http://dummyimage.com/155x100.png/5fa2dd/ffffff",
    brand: "Bombay Selection",
    title: "Offence, The",
    description:
      "Drainage of Left Upper Arm Subcutaneous Tissue and Fascia, Percutaneous Approach, Diagnostic",
    metadata: "Acute hematogenous osteomyelitis, multiple sites",
    trending: false,
    stockQuantity: 92886,
    soldQuantity: 54153,
    price: 58852,
    salePrice: 29835,
    sizes: "XL",
    categories: "T-Shirt",
    rating: 7.99,
  },
  {
    id: 76,
    url: "http://dummyimage.com/189x100.png/dddddd/000000",
    brand: "AND",
    title: "27 Club, The",
    description:
      "Extirpation of Matter from Right Popliteal Artery, Percutaneous Endoscopic Approach",
    metadata: "Unsp inj unsp blood vess at shldr/up arm, right arm, subs",
    trending: true,
    stockQuantity: 36523,
    soldQuantity: 63920,
    price: 52014,
    salePrice: 59421,
    sizes: "XL",
    categories: "Jacket",
    rating: 6.53,
  },
  {
    id: 77,
    url: "http://dummyimage.com/110x100.png/5fa2dd/ffffff",
    brand: "Bombay Selection",
    title: "Elia Kazan: A Director's Journey",
    description:
      "Removal of Monitoring Device from Lower Vein, Percutaneous Endoscopic Approach",
    metadata: "Fracture of xiphoid process, subs for fx w delay heal",
    trending: false,
    stockQuantity: 89389,
    soldQuantity: 60011,
    price: 80678,
    salePrice: 9784,
    sizes: "3XL",
    categories: "Jacket",
    rating: 6.62,
  },
  {
    id: 78,
    url: "http://dummyimage.com/105x100.png/5fa2dd/ffffff",
    brand: "Allen Solly",
    title: "Richie Rich",
    description: "Destruction of Left Metatarsal, Percutaneous Approach",
    metadata: "Matern care for oth or susp poor fetl grth, unsp tri, oth",
    trending: true,
    stockQuantity: 45765,
    soldQuantity: 68767,
    price: 16746,
    salePrice: 96424,
    sizes: "XS",
    categories: "Leggings",
    rating: 8.79,
  },
  {
    id: 79,
    url: "http://dummyimage.com/205x100.png/5fa2dd/ffffff",
    brand: "Allen Solly",
    title: "The True Story of Puss 'n Boots",
    description:
      "Computerized Tomography (CT Scan) of Superior Vena Cava using High Osmolar Contrast",
    metadata: "Child physical abuse, suspected, subsequent encounter",
    trending: false,
    stockQuantity: 14032,
    soldQuantity: 31393,
    price: 81286,
    salePrice: 39725,
    sizes: "XS",
    categories: "Jacket",
    rating: 2.48,
  },
  {
    id: 80,
    url: "http://dummyimage.com/114x100.png/cc0000/ffffff",
    brand: "Pepe Jeans",
    title: "Conjuring, The",
    description:
      "Insertion of Internal Fixation Device into Right Palatine Bone, Percutaneous Endoscopic Approach",
    metadata: "Toxic effect of contact with venomous marine plant",
    trending: false,
    stockQuantity: 70103,
    soldQuantity: 664,
    price: 82127,
    salePrice: 39147,
    sizes: "S",
    categories: "Jacket",
    rating: 1.33,
  },
  {
    id: 81,
    url: "http://dummyimage.com/105x100.png/5fa2dd/ffffff",
    brand: "Levis",
    title: "Muse, The",
    description:
      "Bypass Bilateral Ureters to Bladder with Synthetic Substitute, Open Approach",
    metadata: "Oth fracture of fourth thoracic vertebra, init for opn fx",
    trending: false,
    stockQuantity: 53747,
    soldQuantity: 10137,
    price: 67091,
    salePrice: 88590,
    sizes: "XS",
    categories: "T-Shirt",
    rating: 3.46,
  },
  {
    id: 82,
    url: "http://dummyimage.com/215x100.png/cc0000/ffffff",
    brand: "Chumbak",
    title: "(A)sexual",
    description:
      "Replacement of Left Ankle Tendon with Synthetic Substitute, Percutaneous Endoscopic Approach",
    metadata: "Hypersecretion glaucoma, unspecified eye",
    trending: true,
    stockQuantity: 59842,
    soldQuantity: 38514,
    price: 67285,
    salePrice: 34888,
    sizes: "XS",
    categories: "Skirt",
    rating: 4.44,
  },
  {
    id: 83,
    url: "http://dummyimage.com/238x100.png/dddddd/000000",
    brand: "Madame or Glamly",
    title: "Identification Marks: None (Rysopis) ",
    description:
      "Plain Radiography of Left Internal Mammary Bypass Graft using Low Osmolar Contrast",
    metadata: "Nondisp fx of base of 2nd MC bone, r hand, 7thP",
    trending: false,
    stockQuantity: 32492,
    soldQuantity: 16308,
    price: 13459,
    salePrice: 54157,
    sizes: "XS",
    categories: "Top",
    rating: 7.51,
  },
  {
    id: 84,
    url: "http://dummyimage.com/186x100.png/5fa2dd/ffffff",
    brand: "Madame or Glamly",
    title: "Magic",
    description:
      "Temporal Ordering of Stimuli Assessment using Sound Field / Booth",
    metadata: "Osteopathy in diseases classified elsewhere, forearm",
    trending: false,
    stockQuantity: 98072,
    soldQuantity: 69432,
    price: 32404,
    salePrice: 85406,
    sizes: "S",
    categories: "Saree",
    rating: 7.98,
  },
  {
    id: 85,
    url: "http://dummyimage.com/182x100.png/5fa2dd/ffffff",
    brand: "Pepe Jeans",
    title: "Life of a King",
    description:
      "Replacement of Left Lacrimal Duct with Synthetic Substitute, Via Natural or Artificial Opening",
    metadata: "Necrosis of amputation stump, right upper extremity",
    trending: false,
    stockQuantity: 66854,
    soldQuantity: 31723,
    price: 71258,
    salePrice: 59665,
    sizes: "XS",
    categories: "Jacket",
    rating: 6.14,
  },
  {
    id: 86,
    url: "http://dummyimage.com/211x100.png/ff4444/ffffff",
    brand: "Only",
    title: "My Little Eye",
    description:
      "Restriction of Celiac Artery, Percutaneous Endoscopic Approach",
    metadata: "Unsp inj unsp musc/fasc/tend at forarm lv, right arm, subs",
    trending: false,
    stockQuantity: 58850,
    soldQuantity: 56332,
    price: 29997,
    salePrice: 29648,
    sizes: "XS",
    categories: "Top",
    rating: 4.56,
  },
  {
    id: 87,
    url: "http://dummyimage.com/180x100.png/ff4444/ffffff",
    brand: "H&M",
    title: "Somewhere Under the Broad Sky",
    description:
      "Dilation of Hymen with Intraluminal Device, External Approach",
    metadata: "Partial traumatic MCP amputation of right ring finger",
    trending: false,
    stockQuantity: 54036,
    soldQuantity: 4255,
    price: 20893,
    salePrice: 50398,
    sizes: "L",
    categories: "Skirt",
    rating: 4.27,
  },
  {
    id: 88,
    url: "http://dummyimage.com/229x100.png/5fa2dd/ffffff",
    brand: "Bombay Selection",
    title: "Fly, The",
    description:
      "Bypass Cecum to Ascending Colon with Autologous Tissue Substitute, Open Approach",
    metadata: "Follicular cyst of left ovary",
    trending: true,
    stockQuantity: 48324,
    soldQuantity: 30901,
    price: 6600,
    salePrice: 62153,
    sizes: "XS",
    categories: "Top",
    rating: 5.96,
  },
  {
    id: 89,
    url: "http://dummyimage.com/208x100.png/5fa2dd/ffffff",
    brand: "AND",
    title: "The Spiritual Boxer",
    description:
      "Replacement of Nasal Turbinate with Nonautologous Tissue Substitute, Open Approach",
    metadata: "Lacerat musc/fasc/tend long hd bicep, left arm, sequela",
    trending: true,
    stockQuantity: 61733,
    soldQuantity: 2060,
    price: 71607,
    salePrice: 61944,
    sizes: "S",
    categories: "Hoodie",
    rating: 5.26,
  },
  {
    id: 90,
    url: "http://dummyimage.com/208x100.png/ff4444/ffffff",
    brand: "Chumbak",
    title: "Ferryman, The",
    description: "Drainage of Left External Iliac Artery, Open Approach",
    metadata: "Vitreous abscess (chronic), bilateral",
    trending: false,
    stockQuantity: 57784,
    soldQuantity: 14904,
    price: 94043,
    salePrice: 21820,
    sizes: "S",
    categories: "T-Shirt",
    rating: 9.71,
  },
  {
    id: 91,
    url: "http://dummyimage.com/136x100.png/cc0000/ffffff",
    brand: "W for Women The label - Ritu Kumar",
    title: "East Side, West Side",
    description: "Release Cul-de-sac, Percutaneous Endoscopic Approach",
    metadata: "Missed abortion",
    trending: false,
    stockQuantity: 70179,
    soldQuantity: 8912,
    price: 88460,
    salePrice: 24000,
    sizes: "XS",
    categories: "Hoodie",
    rating: 8.17,
  },
  {
    id: 92,
    url: "http://dummyimage.com/108x100.png/dddddd/000000",
    brand: "W for Women The label - Ritu Kumar",
    title: "It Conquered the World",
    description: "Stereotactic Other Photon Radiosurgery of Head and Neck",
    metadata: "Inj intrinsic musc/fasc/tend finger at wrs/hnd lv, subs",
    trending: true,
    stockQuantity: 18126,
    soldQuantity: 42437,
    price: 44379,
    salePrice: 72384,
    sizes: "S",
    categories: "Skirt",
    rating: 6.04,
  },
  {
    id: 93,
    url: "http://dummyimage.com/229x100.png/ff4444/ffffff",
    brand: "Madame or Glamly",
    title: "Dead End",
    description:
      "Removal of Autologous Tissue Substitute from Right Upper Femur, Percutaneous Approach",
    metadata: "Nondisp fx of neck of left talus, subs for fx w routn heal",
    trending: true,
    stockQuantity: 2987,
    soldQuantity: 49402,
    price: 98597,
    salePrice: 32151,
    sizes: "M",
    categories: "Jacket",
    rating: 7.82,
  },
  {
    id: 94,
    url: "http://dummyimage.com/201x100.png/dddddd/000000",
    brand: "Globus",
    title: "Employees Leaving the Lumière Factory",
    description:
      "Dilation of Coronary Artery, Four or More Arteries, Bifurcation, with Four or More Drug-eluting Intraluminal Devices, Open Approach",
    metadata: "Unsp superficial injuries of right front wall of thorax",
    trending: false,
    stockQuantity: 76314,
    soldQuantity: 50652,
    price: 57093,
    salePrice: 73140,
    sizes: "3XL",
    categories: "Saree",
    rating: 1.41,
  },
  {
    id: 95,
    url: "http://dummyimage.com/207x100.png/5fa2dd/ffffff",
    brand: "W for Women The label - Ritu Kumar",
    title: "50 First Dates",
    description:
      "Dilation of Middle Colic Artery, Bifurcation, with Three Intraluminal Devices, Percutaneous Approach",
    metadata: "Unspecified superficial injury of left forearm, sequela",
    trending: true,
    stockQuantity: 36397,
    soldQuantity: 63487,
    price: 3745,
    salePrice: 34784,
    sizes: "XS",
    categories: "Skirt",
    rating: 7.27,
  },
  {
    id: 96,
    url: "http://dummyimage.com/121x100.png/5fa2dd/ffffff",
    brand: "AND",
    title: "Waiting for Guffman",
    description:
      "Revision of Autologous Tissue Substitute in Left Ulna, Percutaneous Approach",
    metadata: "I/I react d/t implanted urn nstim dev, subsequent encounter",
    trending: false,
    stockQuantity: 69772,
    soldQuantity: 19103,
    price: 51660,
    salePrice: 44992,
    sizes: "M",
    categories: "Underwear",
    rating: 5.4,
  },
  {
    id: 97,
    url: "http://dummyimage.com/229x100.png/cc0000/ffffff",
    brand: "Levis",
    title: "The Virginian",
    description:
      "Insertion of External Fixation Device into Right Upper Femur, Open Approach",
    metadata: "Arthropathies in oth diseases classd elswhr, left wrist",
    trending: true,
    stockQuantity: 63630,
    soldQuantity: 14459,
    price: 61078,
    salePrice: 48419,
    sizes: "S",
    categories: "Skirt",
    rating: 1.11,
  },
  {
    id: 98,
    url: "http://dummyimage.com/141x100.png/ff4444/ffffff",
    brand: "Only",
    title: "George of the Jungle",
    description:
      "Extirpation of Matter from Right Internal Carotid Artery, Bifurcation, Percutaneous Approach",
    metadata: "Unsp open wound of left great toe without damage to nail",
    trending: true,
    stockQuantity: 20238,
    soldQuantity: 1282,
    price: 99777,
    salePrice: 66749,
    sizes: "L",
    categories: "Kurti",
    rating: 8.85,
  },
  {
    id: 99,
    url: "http://dummyimage.com/159x100.png/dddddd/000000",
    brand: "Madame or Glamly",
    title: "Police, Adjective (Politist, adj.)",
    description:
      "Occlusion of Left Lesser Saphenous Vein with Extraluminal Device, Open Approach",
    metadata: "Placentitis, first trimester, fetus 3",
    trending: false,
    stockQuantity: 475,
    soldQuantity: 73443,
    price: 91227,
    salePrice: 1639,
    sizes: "XL",
    categories: "T-Shirt",
    rating: 9.33,
  },
  {
    id: 100,
    url: "http://dummyimage.com/176x100.png/cc0000/ffffff",
    brand: "Only",
    title: "Battle Beyond the Stars",
    description:
      "Introduction of Liquid Brachytherapy Radioisotope into Pericardial Cavity, Percutaneous Approach",
    metadata: "Fracture of unsp part of neck of right femur, init",
    trending: true,
    stockQuantity: 11679,
    soldQuantity: 91378,
    price: 31489,
    salePrice: 51893,
    sizes: "L",
    categories: "Jeans",
    rating: 3.07,
  },
];
